<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<OutputPath>..\bin\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);MSB3277</NoWarn>
	</PropertyGroup>

	<Target Name="CopyFiles" AfterTargets="Build">
		<!-- List files to copy -->
		<ItemGroup Condition="Exists('$(ProjectDir)..\user files\GitHub.conf')">
			<Files Include="$(ProjectDir)..\user files\GitHub.conf" />
		</ItemGroup>

		<!-- Copy them to bin directory -->
		<Copy SourceFiles="@(Files)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
	</Target>

	<PropertyGroup>
		<!-- Redirect AssemblyAttributes.cs so each project has its own -->
		<TargetFrameworkMonikerAssemblyAttributesPath>$(IntermediateOutputPath)$(MSBuildProjectName).AssemblyAttributes.cs</TargetFrameworkMonikerAssemblyAttributesPath>
		<!-- Avoid duplicate TargetFrameworkAttribute -->
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	</PropertyGroup>
	<ItemGroup>
		<!-- Prevent duplicate 'Compile' inclusion of the generated AssemblyAttributes.cs -->
		<Compile Remove="$(IntermediateOutputPath)$(MSBuildProjectName).AssemblyAttributes.cs" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="System.Text.Json" Version="10.0.2" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="DiGi.Core">
	    <HintPath>..\..\DiGi.Core\bin\DiGi.Core.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
